# Generated by Django 4.0.3 on 2022-05-07 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=100, null=True, verbose_name="Title")),
                ("message", models.TextField(blank=True, max_length=1000, null=True, verbose_name="Message")),
                (
                    "admin_response",
                    models.TextField(blank=True, max_length=1000, null=True, verbose_name="Admin Response"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Solved"), (1, "Unsolved"), (2, "Freeze")], default=1, verbose_name="Status"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(blank=True, max_length=1000, null=True, verbose_name="Ticket Message")),
                (
                    "admin_response",
                    models.TextField(blank=True, max_length=1000, null=True, verbose_name="Admin Response"),
                ),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ticket.ticket")),
            ],
            options={
                "verbose_name": "Ticket Comment",
                "verbose_name_plural": "Ticket Comments",
                "ordering": ["-id"],
            },
        ),
    ]
